
package com.kb.ws.client;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PrimeNumberServiceImplService", targetNamespace = "http://ws.kb.com/", wsdlLocation = "http://localhost:8888/ws/primeNumber?wsdl")
public class PrimeNumberServiceImplService
    extends Service
{

    private final static URL PRIMENUMBERSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRIMENUMBERSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName PRIMENUMBERSERVICEIMPLSERVICE_QNAME = new QName("http://ws.kb.com/", "PrimeNumberServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/ws/primeNumber?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRIMENUMBERSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        PRIMENUMBERSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public PrimeNumberServiceImplService() {
        super(__getWsdlLocation(), PRIMENUMBERSERVICEIMPLSERVICE_QNAME);
    }

    public PrimeNumberServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRIMENUMBERSERVICEIMPLSERVICE_QNAME, features);
    }

    public PrimeNumberServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, PRIMENUMBERSERVICEIMPLSERVICE_QNAME);
    }

    public PrimeNumberServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRIMENUMBERSERVICEIMPLSERVICE_QNAME, features);
    }

    public PrimeNumberServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PrimeNumberServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PrimeNumberService
     */
    @WebEndpoint(name = "PrimeNumberServiceImplPort")
    public PrimeNumberService getPrimeNumberServiceImplPort() {
        return super.getPort(new QName("http://ws.kb.com/", "PrimeNumberServiceImplPort"), PrimeNumberService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PrimeNumberService
     */
    @WebEndpoint(name = "PrimeNumberServiceImplPort")
    public PrimeNumberService getPrimeNumberServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.kb.com/", "PrimeNumberServiceImplPort"), PrimeNumberService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRIMENUMBERSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw PRIMENUMBERSERVICEIMPLSERVICE_EXCEPTION;
        }
        return PRIMENUMBERSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
