/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.pradeep.gradle;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Product p = new Product();
        p.setName("Samsung TV");
        p.setPrice(55000.00d);
        p.setDescription("For Watching Movies & Serials");
        System.out.println(new App().getGreeting());
        System.out.println(p);
    }
}
